DROP TABLE IF EXISTS QUESTIONS;
DROP TABLE IF EXISTS ALTERNATIVES;

CREATE TABLE QUESTIONS (
    ID_QUESTION INTEGER AUTO_INCREMENT PRIMARY KEY,
    TEXT_QUESTION VARCHAR(500),
    RIGHT_ANSWER INTEGER,
    WRONG_ANSWER INTEGER,
    NU_ANSWER INTEGER,
    OPTION_A VARCHAR(255),
    OPTION_B VARCHAR(255),
    OPTION_C VARCHAR(255),
    OPTION_D VARCHAR(255),
    OPTION_E VARCHAR(255)
);

